# Generated by Django 5.0.1 on 2024-03-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_to_agents',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_to_users',
            field=models.BooleanField(default=True),
        ),
    ]
