# Generated by Django 5.0.3 on 2024-03-19 20:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("departure_city", models.CharField(max_length=100)),
                ("arrival_city", models.CharField(max_length=100)),
                (
                    "departure_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 3, 19, 20, 9, 24, 39371, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "arrival_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 3, 19, 23, 9, 24, 39371, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["departure_time"],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "checkinDate",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 3, 19, 20, 9, 24, 41383, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "checkoutDate",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 3, 20, 20, 9, 24, 41383, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("occupancy", models.IntegerField(default=1)),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Modification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Client", models.CharField(max_length=50)),
                ("request", models.TextField()),
                ("Request_creation_Date_Time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookingAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user"],
            },
        ),
        migrations.CreateModel(
            name="TravelPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=1122.0, max_digits=10
                    ),
                ),
                (
                    "activities",
                    models.ManyToManyField(blank=True, to="travelAgencyApi.activity"),
                ),
                ("flights", models.ManyToManyField(to="travelAgencyApi.flight")),
                ("hotels", models.ManyToManyField(to="travelAgencyApi.hotel")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BookingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_status_flag", models.BooleanField(default=False)),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="travelAgencyApi.bookingagent",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "travel_package",
                    models.ManyToManyField(to="travelAgencyApi.travelpackage"),
                ),
            ],
            options={
                "ordering": ["customer"],
            },
        ),
    ]
