# Generated by Django 4.1 on 2024-02-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.URLField(help_text='Enter the URL of the image', max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
