# Generated by Django 5.0.1 on 2024-02-15 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travelAgencyApi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["departure_time"]},
        ),
        migrations.AlterModelOptions(
            name="hotel",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="travelpackage",
            options={"ordering": ["name"]},
        ),
    ]
