# Generated by Django 5.0.1 on 2024-02-15 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "travelAgencyApi",
            "0002_alter_activity_options_alter_flight_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="checkinDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 15, 19, 42, 23, 129648, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="checkoutDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 16, 19, 42, 23, 129648, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="occupancy",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 15, 22, 42, 23, 128623, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 15, 19, 42, 23, 128623, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
