# Generated by Django 5.0.1 on 2024-02-18 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "travelAgencyApi",
            "0003_hotel_checkindate_hotel_checkoutdate_hotel_occupancy_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("notification", models.CharField(default="info", max_length=250)),
                ("Date_Time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["Date_Time"],
            },
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 18, 23, 9, 21, 111521, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 18, 20, 9, 21, 111521, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="checkinDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 18, 20, 9, 21, 111521, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="checkoutDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 19, 20, 9, 21, 111521, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
