# Generated by Django 4.2.7 on 2024-03-22 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelAgencyApi', '0004_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 18, 6, 59, 744546, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 21, 6, 59, 737042, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 18, 6, 59, 736463, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='checkinDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 18, 6, 59, 738104, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='checkoutDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 18, 6, 59, 738143, tzinfo=datetime.timezone.utc)),
        ),
    ]
