# Generated by Django 5.0.1 on 2024-02-19 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travelAgencyApi", "0006_alter_flight_arrival_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="arrival_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 19, 8, 14, 48, 862384, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 19, 5, 14, 48, 862384, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="checkinDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 19, 5, 14, 48, 863313, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="checkoutDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 20, 5, 14, 48, 863313, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
