# Generated by Django 5.0.1 on 2024-02-21 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travelAgencyApi", "0011_alter_flight_arrival_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelpackage",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1122.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 21, 19, 26, 57, 380550, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 21, 16, 26, 57, 380550, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="checkinDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 21, 16, 26, 57, 381569, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="checkoutDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 22, 16, 26, 57, 381569, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
