# Generated by Django 5.0.1 on 2024-02-21 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travelAgencyApi", "0015_alter_flight_arrival_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingdetails",
            options={"ordering": ["customer"]},
        ),
        migrations.RemoveField(
            model_name="bookingdetails",
            name="travel_package",
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 21, 23, 30, 10, 628770, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 21, 20, 30, 10, 628770, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="checkinDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 21, 20, 30, 10, 628770, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="checkoutDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 22, 20, 30, 10, 628770, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="bookingdetails",
            name="travel_package",
            field=models.ManyToManyField(to="travelAgencyApi.travelpackage"),
        ),
    ]
