# Generated by Django 5.0.3 on 2024-03-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticationBackend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Agent", "Agent"), ("User", "User")],
                default="User",
                max_length=5,
            ),
        ),
    ]
