# Generated by Django 5.0.3 on 2024-04-02 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationBackend', '0003_remove_user_user_type_user_is_admin_user_is_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_user',
        ),
    ]
