# Generated by Django 5.0.3 on 2024-04-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationBackend', '0004_remove_user_is_admin_remove_user_is_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Agent', 'Agent'), ('User', 'User')], default='User', max_length=5),
        ),
    ]
